controller_list:
  - name: arm_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [robot1_tf/shoulder_pan_joint, robot1_tf/shoulder_lift_joint, robot1_tf/elbow_joint, robot1_tf/wrist_1_joint, robot1_tf/wrist_2_joint, robot1_tf/wrist_3_joint]